CREATE TABLE IF NOT EXISTS jira_issue_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_id VARCHAR(64) NOT NULL,
    issue_key VARCHAR(64) NOT NULL,
    issue_type VARCHAR(128),
    status VARCHAR(128),
    project_key VARCHAR(128),
    project_name VARCHAR(256),
    summary VARCHAR(2000),
    story_points DOUBLE,
    sprint VARCHAR(512),
    assignee VARCHAR(256),
    sso VARCHAR(256),
    resolved_at TIMESTAMP,
    month_number INTEGER,
    month_name VARCHAR(64),
    to_do_to_in_progress_at TIMESTAMP,
    in_progress_to_validation_at TIMESTAMP,
    validation_to_done_at TIMESTAMP,
    jira_cycle_time_days DOUBLE,
    jira_updated_at TIMESTAMP,
    last_synced_at TIMESTAMP,
    CONSTRAINT uk_jira_issue_record_issue_id UNIQUE (issue_id),
    CONSTRAINT uk_jira_issue_record_issue_key UNIQUE (issue_key)
);

CREATE TABLE IF NOT EXISTS project (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_key VARCHAR(128) NOT NULL,
    project_name VARCHAR(256) NOT NULL,
    CONSTRAINT uk_project_project_key UNIQUE (project_key)
);

CREATE TABLE IF NOT EXISTS sso_userid (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    sso VARCHAR(255) NOT NULL,
    bitbucket_user_id VARCHAR(100) NOT NULL,
    last_synced_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_sso_userid UNIQUE (project_id, sso)
);

CREATE INDEX IF NOT EXISTS idx_sso_userid_project
    ON sso_userid(project_id);

CREATE INDEX IF NOT EXISTS idx_sso_userid_bitbucket
    ON sso_userid(bitbucket_user_id);

CREATE TABLE IF NOT EXISTS bitbucket_pr (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    project_key VARCHAR(128) NOT NULL,
    repository_name VARCHAR(256),
    repo_slug VARCHAR(256) NOT NULL,
    pr_id BIGINT NOT NULL,
    author_name VARCHAR(256),
    author_username VARCHAR(256),
    title VARCHAR(2000),
    description CLOB,
    source_branch VARCHAR(512),
    destination_branch VARCHAR(512),
    state VARCHAR(64),
    jira_key VARCHAR(128),
    jira_mapping_source VARCHAR(64),
    pr_created_at TIMESTAMP WITH TIME ZONE,
    first_commit_at TIMESTAMP WITH TIME ZONE,
    first_review_engagement_at TIMESTAMP WITH TIME ZONE,
    pr_merged_at TIMESTAMP WITH TIME ZONE,
    cycle_start TIMESTAMP WITH TIME ZONE,
    cycle_start_source VARCHAR(64),
    cycle_time_days DOUBLE,
    last_synced_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_bitbucket_pr_natural_key UNIQUE (project_key, repo_slug, pr_id)
);

CREATE INDEX IF NOT EXISTS idx_bitbucket_pr_project
    ON bitbucket_pr(project_id);
