package com.jira.analytics.service;

import jakarta.annotation.PostConstruct;
import java.util.List;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Component
public class BitbucketSchemaMigrationService {

    private final JdbcTemplate jdbcTemplate;

    public BitbucketSchemaMigrationService(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    @PostConstruct
    public void migrate() {
        runStatements(List.of(
                """
                CREATE TABLE IF NOT EXISTS bitbucket_project (
                    project_key VARCHAR(255) PRIMARY KEY,
                    project_name VARCHAR(500),
                    active BOOLEAN DEFAULT TRUE,
                    last_discovered_at TIMESTAMP WITH TIME ZONE
                )
                """,
                """
                CREATE TABLE IF NOT EXISTS bitbucket_repository (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    project_key VARCHAR(255) NOT NULL,
                    repo_slug VARCHAR(500) NOT NULL,
                    repo_name VARCHAR(500),
                    active BOOLEAN DEFAULT TRUE,
                    last_discovered_at TIMESTAMP WITH TIME ZONE,
                    CONSTRAINT uk_bitbucket_repo UNIQUE(project_key, repo_slug)
                )
                """,
                """
                CREATE TABLE IF NOT EXISTS bitbucket_user_repo_activity (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    bitbucket_username VARCHAR(255) NOT NULL,
                    project_key VARCHAR(255) NOT NULL,
                    repo_slug VARCHAR(500) NOT NULL,
                    last_pr_seen_at TIMESTAMP WITH TIME ZONE,
                    last_scanned_at TIMESTAMP WITH TIME ZONE,
                    CONSTRAINT uk_user_repo_activity UNIQUE(bitbucket_username, project_key, repo_slug)
                )
                """
        ));

        addColumnIfMissing("sso_userid", "bitbucket_username VARCHAR(255)");
        addColumnIfMissing("sso_userid", "bitbucket_slug VARCHAR(255)");
        addColumnIfMissing("sso_userid", "last_resolved_at TIMESTAMP WITH TIME ZONE");
        addColumnIfMissing("bitbucket_pr", "application_project_id BIGINT");
        addColumnIfMissing("bitbucket_pr", "project_name VARCHAR(500)");
        addColumnIfMissing("bitbucket_pr", "author_user_id VARCHAR(100)");

        runStatements(List.of(
                "CREATE INDEX IF NOT EXISTS idx_sso_userid_project ON sso_userid(project_id)",
                "CREATE INDEX IF NOT EXISTS idx_sso_userid_bitbucket ON sso_userid(bitbucket_user_id)",
                "CREATE INDEX IF NOT EXISTS idx_bitbucket_pr_project ON bitbucket_pr(application_project_id)"
        ));
    }

    private void runStatements(List<String> statements) {
        for (String statement : statements) {
            jdbcTemplate.execute(statement);
        }
    }

    private void addColumnIfMissing(String tableName, String columnDefinition) {
        jdbcTemplate.execute("ALTER TABLE " + tableName + " ADD COLUMN IF NOT EXISTS " + columnDefinition);
    }
}
